test_format = 1.0

[default]
    args.domain = "domain.tld"
    args.path = "/blog"
    args.init_main_permission = "visitors"
    args.admin_usernames = ""

[default.test_upgrade_from]

[multi]
    args.domain = "domain.tld"
    args.path = "/reviews"
    args.init_main_permission = "visitors"
    args.admin_usernames = ""

[root_install]
    args.domain = "domain.tld"
    args.path = "/"
    args.init_main_permission = "visitors"
    args.admin_usernames = ""
