/**
 * Production Environment — generated by YunoHost install/upgrade.
 * __API_PATH__ is replaced at build time by the install/upgrade script.
 */
import { IEnvironment } from './environment.interface';

export const environment: IEnvironment = {
  production: true,
  apiUrl: '__API_PATH__',
  features: {
    markdownPreview: true,
    adminAnalytics: true,
  },
};
