/**
 * Production Environment — generated by YunoHost install/upgrade.
 * __API_PATH__ and __DOMAIN__ are replaced at build time by the install script.
 */
export const environment = {
  production: true,
  apiUrl: '__API_PATH__',
  ssoLoginUrl: 'https://__DOMAIN__/yunohost/sso/',
  ssoLogoutUrl: 'https://__DOMAIN__/yunohost/sso/?action=logout',
};
