#!/bin/bash
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# BACKUP THE APP MAIN DIR
#=================================================
ynh_script_progression --message="Backing up the app..." --weight=5

ynh_backup --src_path="$install_dir"

#=================================================
# BACKUP SYSTEM CONFIGURATION
#=================================================

ynh_backup --src_path="/etc/nginx/conf.d/$domain.d/$app.conf"
ynh_backup --src_path="/etc/systemd/system/$app.service"

#=================================================
# BACKUP THE DATABASE
#=================================================
ynh_script_progression --message="Backing up the database..." --weight=5

ynh_mysql_dump_db > db.sql

#=================================================
# END
#=================================================
ynh_script_progression --message="Backup completed!" --last
