#!/bin/bash
source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# UPDATE NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Updating NGINX configuration..." --weight=5

ynh_change_url_nginx_config

#=================================================
# END
#=================================================
ynh_script_progression --message="URL change completed!" --last
