#!/bin/bash
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE NODE.JS
#=================================================
ynh_script_progression --message="Reinstalling Node.js..." --weight=10

ynh_install_nodejs --nodejs_version=$nodejs_version

#=================================================
# RESTORE FILES
#=================================================
ynh_script_progression --message="Restoring files..." --weight=5

ynh_restore_file --origin_path="$install_dir"

chown -R $app:www-data "$install_dir/www"
chmod -R 750 "$install_dir/www"
chown $app:$app "$install_dir/api"
chown -R $app:$app "$install_dir/api"
chown $app:www-data "$install_dir"
chmod 750 "$install_dir"

#=================================================
# RESTORE THE DATABASE
#=================================================
ynh_script_progression --message="Restoring the database..." --weight=5

ynh_mysql_connect_as "$db_user" "$db_pwd" "$db_name" < ./db.sql

#=================================================
# RESTORE NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Restoring NGINX configuration..." --weight=2

ynh_restore_file --origin_path="/etc/nginx/conf.d/$domain.d/$app.conf"
ynh_systemd_action --service_name=nginx --action=reload

#=================================================
# RESTORE SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Restoring systemd service..." --weight=1

ynh_restore_file --origin_path="/etc/systemd/system/$app.service"
systemctl enable "$app.service" --quiet
systemctl daemon-reload

#=================================================
# START API
#=================================================
ynh_script_progression --message="Starting API service..." --weight=1

ynh_systemd_action --service_name=$app --action=start --log_path=systemd

#=================================================
# END
#=================================================
ynh_script_progression --message="Restoration completed!" --last
