#!/bin/bash
source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE NODE.JS
#=================================================
ynh_script_progression --message="Reinstalling Node.js..." --weight=10

ynh_install_nodejs --nodejs_version=$nodejs_version

#=================================================
# RESTORE FILES
#=================================================
ynh_script_progression --message="Restoring files..." --weight=5

ynh_restore_file --origin_path="$install_dir"

chown -R $app:www-data "$install_dir/www"
chmod -R 750 "$install_dir/www"

#=================================================
# RESTORE NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Restoring NGINX configuration..." --weight=2

ynh_restore_file --origin_path="/etc/nginx/conf.d/$domain.d/$app.conf"
ynh_systemd_action --service_name=nginx --action=reload

#=================================================
# START API
#=================================================
ynh_script_progression --message="Starting API service..." --weight=1

ynh_systemd_action --service_name=$app --action=start --log_path=systemd

#=================================================
# END
#=================================================
ynh_script_progression --message="Restoration completed!" --last
