#!/bin/bash
source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# BACKUP THE APP
#=================================================
ynh_script_progression --message="Backing up the app..." --weight=5

ynh_backup --src_path="$install_dir"
ynh_backup --src_path="/etc/nginx/conf.d/$domain.d/$app.conf"

#=================================================
# END
#=================================================
ynh_script_progression --message="Backup completed!" --last
